import { dbConnect } from "@/services/mongodb";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect();

  return (
    <html lang="en">
      <body className={`bg-gray-50 antialiased`}>{children}</body>
    </html>
  );
}
