import Providers from "@/lib/providers/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={`bg-gray-50 antialiased`}>
          <>
          {children}
          <Toaster position="top-left" />
          </>
          </body>
      </html>
    </Providers>
  );
}
